/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PackageInfo {
  dependencies?: Record<string, string>
  devDependencies?: Record<string, string>
  name: string
  private?: boolean
  peerDependencies?: Record<string, string>
  version: string
  packageJsonPath?: string
}
export function getWorkspaces(cwd: string): Array<PackageInfo>
